### ISSUE TITLE
I changed the bungeecord option to false...

### ISSUE THREAD

**Issue by wattywatty14** [Efnilite/Walk-in-the-Park#1]
I changed the bungeecord option to false and it just broke the plugin after I restarted the server. The scoreboard won't work, the GUI menu won't work... please help. Thanks. :)

**Comment by Efnilite** [comment]
Hello there,
Please open a new issue using the "Bug template" issue template so I can get more information. Please check first if you have the latest version (you can update by checking https://www.spigotmc.org/resources/walk-in-the-park-infinite-parkour.87226/) first.

**Comment by Efnilite** [comment]
Okay as it turns out this is all the information I needed. I have this problem even on the latest version - I'll be fixing it right away.

**Comment by wattywatty14** [comment]
Thank you! :)

**Comment by Efnilite** [comment]
Well it's not really a bug, it's just that because bungeecord is off you don't join the game, but you get teleported to the last position you were in by the server automatically. I'll make it so people who haven't joined the game can't go to the world, which shouldn't take long.

**Comment by Efnilite** [comment]
Fixed in [latest commit](https://github.com/Efnilite/Walk-in-the-Park/commit/8796b95c63bfaf6498ddafe514f5fe322112abab), thanks for reporting!
