### ISSUE TITLE
player met border

### ISSUE THREAD

**Issue by WongIong** [Efnilite/Walk-in-the-Park#100]
**Describe the bug**

**To Reproduce**
1. Play the Parkour normally
2. when the player goes to 171 blocks, there were a border

**Screenshots**
![image](https://github.com/Efnilite/Walk-in-the-Park/assets/36799194/afcdca20-4754-490e-a448-3dd004240eac)

**Errors**
no errors

**Versions** 
- Plugin version 5.0.0
- Spigot/Paper version paper 1.17.1

**Additional context**

**Comment by Efnilite** [comment]
Can you send your `generation.yml` file?

**Comment by WongIong** [comment]
# -= Parkour Generation Settings =-
# Settings for parkour generation
generation:
  
  # -= Jump type =-
  # The chance of each type of jump. Can be above 100%.
  type:
    
    # -= Normal jump chances =-
    normal: 85
    special: 10
    schematic: 5
  normal:
    distance:
      '1': 10
      '2': 55
      '3': 34
      '4': 1
    height:
      '1': 20
      '0': 65
      '-1': 10
      '-2': 5
  special:
    ice: 50
    slab: 30
    pane: 10
    fence: 10
  settings:
    min-y: 100
    max-y: 200

# -= Advanced settings =-
# Don't modify these if you don't know what you're doing!
advanced:
  
  # -= Spawn island options =-
  # Options for the spawn island
  island:
    spawn:
      
      # -= Player block =-
      # The material of the block that the player will spawn on.
      # This block will be set to air once the schematic has been pasted.
      player-block: diamond_block
      
      # -= Spawn yaw/pitch =-
      yaw: -90
      pitch: 0
    
    parkour:
      
      # -= Begin block =-
      # The block from which the parkour begins
      # This block will be set to air once the schematic has been pasted
      begin-block: emerald_block
      
      # -= Directional heading =-
      # The directional heading of the parkour
      # Possible options: north, south, west and east.
      heading: east
  
  # -= Border size =-
  # The diameter of the playing area of a person in the single mode.
  border-size: 10000
  
  # -= Schematic cooldown =-
  # The amount of blocks that provide a cooldown for the schematics.
  schematic-cooldown: 20
  
  # -= Generator check interval =-
  # The amount of ticks between checks of the player's location and score.
  # Lowering this is not recommended. Raising this may cause additional lag.
  generator-check: 2

**Comment by Efnilite** [comment]
I'm not sure how but the world border could've been set at a really small size due to other plugins. https://github.com/Efnilite/Walk-in-the-Park/commit/c7aacae55432d85e0cc8c37b410d6764fa39984b explicitly sets the world border's size to 10 million, which should fix it.

**Comment by WongIong** [comment]
thx

**Comment by WongIong** [comment]
I compiled it, and tested. I still can meet the border while 163 points

**Comment by WongIong** [comment]
![image](https://github.com/Efnilite/Walk-in-the-Park/assets/36799194/f7e71cc0-d1d6-494b-88a7-f6565bc2497b)
it shows that the border is 10000000 and my position is
![image](https://github.com/Efnilite/Walk-in-the-Park/assets/36799194/276c8366-b2cc-4c69-b105-c1141919628b)

**Comment by Efnilite** [comment]
Huh, can you send your plugin list? I believe this is being caused by another plugin.

**Comment by WongIong** [comment]
Oh wait, i may know why

**Comment by WongIong** [comment]
Sorry, that was my wrong setting. I have set the max-world-size to 500 = = that's why it would have a border there

**Comment by Efnilite** [comment]
Glad you fixed it :)
