### ISSUE TITLE
Issues with spectating

### ISSUE THREAD

**Issue by DrakePork** [Efnilite/Walk-in-the-Park#101]
**Describe the bug**
If a player has a lobby open, and someone else joins(who doesnt have ip.admin) from a different world, they'll get kicked with the reason "You can't enter the parkour world by teleporting!" which btw the message is hardcoded into the plugin, it doesn't get the message from the locale.

However, the issue is that if they try to join(if they're in a different world). a multiplayer lobby, or try to join a singleplayer lobby twice, it'll start spamming the console with the error message below about 2 times a second when the lobby owner leaves infinite parkour. 

This also causes phantom lobbies to appear, which is what's causing the warn spam.

**To Reproduce**
1. Create lobby
2. Have someone without ip.admin try to join that lobby from different world twice (or once if multiplayer AND the game has started)
3. Leave infinite parkour
4. Warnings appear

**Errors**
https://mclo.gs/AGRMD7a

**Versions**
- Plugin version: 5.0.0
- Spigot/Paper version: 119.4

**Additional context**
Seems like PlayerChangedWorldEvent is kicking in before ParkourSpectator initializes the ParkourUser

**Comment by Efnilite** [comment]
This has already been fixed. You'll see it in the next release.
