### ISSUE TITLE
Inventory click error vilib

### ISSUE THREAD

**Issue by abola2** [Efnilite/Walk-in-the-Park#105]
**Describe the bug**

**Errors**
(https://pastebin.com/X1wYbu9h)

**Versions**
- vilib v1.2.0
- IP-5.1.0
- paper 1.19.4

(Discord invite doesn't work)

**Comment by Efnilite** [comment]
Where did you find the discord invite? New link is https://efnilite.dev/discord

**Comment by Efnilite** [comment]
It seems you may have made a mistake while trying to add a language translation. The `sort.values` value should have 3 items, while the error says that there are only 2. Try deleting this line from the locale file to and restarting the server to make it regenerate to the default value and adjust it from there.
