### ISSUE TITLE
Decentholograms support [FEATURE REQUEST]

### ISSUE THREAD

**Issue by abola2** [Efnilite/Walk-in-the-Park#106]
Add Decentholograms support https://github.com/DecentSoftware-eu/DecentHolograms

![image](https://github.com/Efnilite/Walk-in-the-Park/assets/81980535/8aafaf4d-a213-4ad1-9e4d-f1c480c8fafa)

**Comment by Efnilite** [comment]
DecentHolograms has PAPI placeholder support.
