### ISSUE TITLE
Scoreboard is blank and never comes back

### ISSUE THREAD

**Issue by TangledWiresYT** [Efnilite/Walk-in-the-Park#109]
**Describe the bug**
I have a scoreboard that I made with skript, but when I join the parkour, it disappears and only comes back if I leave and rejoin.

**To Reproduce**
1. Use /parkour
2. Join parkour
3. Scoreboard disappears

**Screenshots**
![Screenshot 2023-08-26 104121](https://github.com/Efnilite/Walk-in-the-Park/assets/68852080/927eca51-8499-41e3-a129-1699ce4b4058)
![Screenshot 2023-08-26 104154](https://github.com/Efnilite/Walk-in-the-Park/assets/68852080/28768747-a1a0-4b44-97d8-0a8ec5b9b5fd)

**Errors**
No errors

**Versions**
- Plugin version: 5.1.0
- Spigot/Paper version: 1.20.1

**Additional context**
None

**Comment by TangledWiresYT** [comment]
Fixed by editing my script to only show the scoreboard to players not in the parkour world

**Comment by TangledWiresYT** [comment]
Nevermind, it's still happening

**Comment by Efnilite** [comment]
> Fixed by editing my script to only show the scoreboard to players not in the parkour world

Maybe add `wait 1 tick` when a player leaves the parkour?

**Comment by TangledWiresYT** [comment]
It updates the scoreboard every 2 seconds, so I don't think that would change anything, I also tried an update with a command but nothing changed.

**Comment by Efnilite** [comment]
Can you maybe send your Skript code?

**Comment by TangledWiresYT** [comment]
> Can you maybe send your Skript code?

```
function updateScoreboard(p: player):
	#check if the player isn't in the parkour world
	clear {_p}'s scoreboard
	set title of {_p}'s scoreboard to "&6&lWired&r&3Gens"
	set line 11 of {_p}'s scoreboard to "  &8&m-----------------"
	set line 10 of {_p}'s scoreboard to "&6&l%{_p}%"
	set line 9 of {_p}'s scoreboard to " &bBalance:&f %balance of {_p}%"
	set line 8 of {_p}'s scoreboard to " &bMultiplier:&f %{multiplier::%{_p}'s uuid%}%x"
	set line 7 of {_p}'s scoreboard to " &bGen slots:&f %{generator::max::%{_p}'s uuid%}%/%{generator::maximumGens::%{_p}'s uuid%}%"
	set line 6 of {_p}'s scoreboard to " &bTokens:&f %{tokens::%{_p}'s uuid%}%"
	set line 5 of {_p}'s scoreboard to " "
	set line 4 of {_p}'s scoreboard to "&6&lServer" 
	set line 3 of {_p}'s scoreboard to " &bTotal Players: &f%size of all offline players%"
	set line 2 of {_p}'s scoreboard to " &bItems Sold:&f %{globalItemsSold}%"
	set line 1 of {_p}'s scoreboard to "  &8&m-----------------"

every 2 second:
	loop all players:
		if "%loop-player's world%" is not "witp":
			updateScoreboard(loop-player)
		
command /reloadscoreboard:
	permission: wirednetwork.reloadscoreboard
	permission message: &cYou don't have permission to use this command.
	trigger:
		updateScoreboard(player)
		send "Your scoreboard was reloaded" to player

```

**Comment by Efnilite** [comment]
You can disable the scoreboard in the `default-values` section of the config. (set both to false)
