### ISSUE TITLE
Allow whitelisting certain commands for focus-mode.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#11]
Would it be possible to allow whitelisting a certain list of commands when using focus-mode? You may want to block all commands by default to prevent any form of abuse (such as gamemode, teleporting, flying, etc) but are okay with players being able to message, talk in certain chat channels, and reply to players in tells.

```
# Options for focus mode
focus-mode:

    # If focus mode is enabled players can't use commands while in parkour
    enabled: true
```

**Comment by Efnilite** [comment]
Added in https://github.com/Efnilite/Walk-in-the-Park/commit/2b52017552c2db46b0a080451719332856be4fdc.

**Comment by mibby** [comment]
Thanks, super fast! Do you have a jenkins for dev builds or can you enable github action artifacts?

**Comment by Efnilite** [comment]
No, because usually commits I do still require a bunch of testing and usually don't work too well very often. You can expect a new release in ~2-4 days.
