### ISSUE TITLE
Duels

### ISSUE THREAD

**Issue by Volc94** [Efnilite/Walk-in-the-Park#111]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Errors**
Check your console for errors that might've occured. These could help greatly in finding the issue.

**Versions**
- Plugin version
- Spigot/Paper version

**Additional context**

Paper: 1.20.1
Vlib: 1.20
IP: 5.1.1
IP+: 2.1.2
PlaceholderAPI: 2.11.5

- When a duel is started by one player, no others can join. 
- The player joins the duel and no hot-bar icons appear from Parkour. 
- No open lobbies appear and the open lobbies button can not even be used. 

- When exiting a duel, the plugin believes the player has not left and therefore the player is immune to all forms of normal damage. Only exiting the server causes the player to properly sync.
<img width="474" alt="Screen Shot 2023-12-04 at 11 09 16 AM" src="https://github.com/Efnilite/Walk-in-the-Park/assets/120126818/9d062442-05fb-4ade-80aa-f206c914825e">
<img width="517" alt="Screen Shot 2023-12-04 at 11 10 22 AM" src="https://github.com/Efnilite/Walk-in-the-Park/assets/120126818/cf522434-3db0-4c9f-af9f-efa3d6cfbd75">
Second picture shows the player has exited parkour and can still see parkour game options as if still in the game.

[message-5.txt](https://github.com/Efnilite/Walk-in-the-Park/files/13548850/message-5.txt)
[message-6.txt](https://github.com/Efnilite/Walk-in-the-Park/files/13550859/message-6.txt)

- Disabling Duels in IP+ does not work.

**Comment by Volc94** [comment]
[message-6.txt](https://github.com/Efnilite/Walk-in-the-Park/files/13550857/message-6.txt)

**Comment by Efnilite** [comment]
Should be fixed in v5.1.2.
