### ISSUE TITLE
Blocks / structures do not clean up themselves after falling.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#12]
**Describe the bug**
Sometimes blocks & structures do not clean up after themselves / get removed when far enough away or resetting.

**To Reproduce**
1. Play for awhile.
2. See blocks / structures that aren't wiped.

Not too sure if it's caused from playing often or from the server restarting while being in a parkour map.

**Screenshots**

Here are screenshots from a player currently playing after I teleported to them.
![link](https://i.imgur.com/1niEPYW.png)
![link2](https://i.imgur.com/WRVXc4F.png)

**Errors**
None

**Versions**
- WalkInThePark 2.0
- Paper dev 467 (Spigot 1.16.5)

**Comment by Efnilite** [comment]
This is a known issue, I'm currently working on reworking the entire structure/block removal process (although for me this has never happened)

**Comment by mibby** [comment]
So should I just delete the world and let it recreate once it's fixed?

**Comment by Efnilite** [comment]
The world usually gets deleted on restart, but doing it manually is a good enough fix for now I guess

**Comment by mibby** [comment]
Great, let me know if you need any help testing any fix for it since it seems to exist in my environment.

**Comment by mibby** [comment]
Some more screenshots of leftover individual single prismarine blocks. So it looks to be at first glance both schematics and individual generation.

![link3](https://i.imgur.com/alu941y.png)
![link4](https://i.imgur.com/MRg97yt.png)

**Comment by Leomelonseeds** [comment]
+1. This issue is most easily reproduceable with a high lead, for example 10.

**Comment by Efnilite** [comment]
Fixed with latest schematic update. Issue turned out to be players not jumping on the ending red wool and continuing parkour. Thanks for reporting! <3
