### ISSUE TITLE
MySQL Error when sending query INSERT INTO

### ISSUE THREAD

**Issue by FunkyNico** [Efnilite/Walk-in-the-Park#122]
**Describe the bug**
I was playing the parkour and then when i changed some settings for the parkour, like the blocks, etc. The console output some MySQL errors.

**To Reproduce**
1. Go to the parkour single-player.
2. Play some time.
3. Change the settings like amount of blocks generated, color, etc.
4. See the console for MySQL errors.

**Errors**
https://mclo.gs/fWAWXo5

**Versions**
- Plugin version: v5.2.2
- Spigot/Paper version: git-Purpur-2176 (MC: 1.20.4)
- Java: OpenJDK Runtime Environment GraalVM CE 21.0.2+13.1

**Comment by Efnilite** [comment]
This has been fixed and will be available in the next version.
