### ISSUE TITLE
Update Check blocking main thread

### ISSUE THREAD

**Issue by modcrafts** [Efnilite/Walk-in-the-Park#130]
**Describe the bug**
this plugin is doing the update check in main thread, when theres network connection problom it will block the server thread

**To Reproduce**
Start server when unable to access the update server

**Errors**
```
[07:10:36 INFO]: [IP] Checking for updates
[07:11:34 WARN]: [spark] Timed out waiting for world statistics
[07:12:34 WARN]: [spark] Timed out waiting for world statistics
[07:13:34 WARN]: [spark] Timed out waiting for world statistics
[07:14:34 WARN]: [spark] Timed out waiting for world statistics
```

**Versions**
- Latest
- git-Purpur-2076 (MC: 1.20.2)

**Additional context**
btw you can add a option to disable update checking

**Comment by Efnilite** [comment]
Oops! Thanks for reporting

**Comment by Hikari16665** [comment]
new release or build pls!

**Comment by modcrafts** [comment]
> new release or build pls!

https://github.com/modcrafts/Walk-in-the-Park/actions/runs/10171789224
heres a fork that i removed the Update Check and built by GitHub Actions, you can download it here :)

**Comment by Hikari16665** [comment]
> > new release or build pls!
> 
> https://github.com/modcrafts/Walk-in-the-Park/actions/runs/10171789224 heres a fork that i removed the Update Check and built by GitHub Actions, you can download it here :)

thank you
