### ISSUE TITLE
last page of leaderboard is able to taken

### ISSUE THREAD

**Issue by rudde0** [Efnilite/Walk-in-the-Park#132]
**Describe the bug**
GUI items are stealable when we can use pagination

**To Reproduce**
1. Open leaderboard
2. Access to last page via next page button very fastly
3. Take lime dye, player heads etc. to your inventory

**Screenshots**
-

**Errors**
No error

**Versions**
- 5.2.5
- 1.20.4

**Additional context**
I'm using MySQL as storage

**Comment by Efnilite** [comment]
Fixed in next version. Thanks for reporting!
