### ISSUE TITLE
No key layers in MapLike[{}]; No key structures in MapLike[{}]; Not a registry ops

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#15]
WITP compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/3c8ad143059f6656ea7bbc0ef65747f9f5986edb

```
[06:12:48] [Server thread/INFO]: [WITP] Enabling WITP v2.0
[06:12:48] [Server thread/INFO]: [WITP] Downloaded all config files
[06:12:48] [Server thread/INFO]: [WITP] Downloading all structures...
[06:12:48] [Server thread/ERROR]: No key layers in MapLike[{}]; No key structures in MapLike[{}]; Not a registry ops
[06:12:51] [Server thread/INFO]: Preparing start region for dimension minecraft:witp
```

Also need to update the plugin.yml version to v2.1. :)

**Comment by Efnilite** [comment]
Idk why this happens, internet says something with using flat in the world generator, but I have to do that. This happens to everyone (it's not a bug)

**Comment by mibby** [comment]
How does Multiverse generate flat worlds without this error? Would it be possible to copy that generator code or hook into it?

**Comment by Efnilite** [comment]
Well, Multiverse probably doesn't just use generator settings, it uses a bunch of tricky reflection stuff (if I remember correctly). I've made a custom generator as well which creates a void world but for some users it wouldn't create the world to void and set it to a default world. With a default world, mountains exist, so if it wasn't a flat world the parkour _could in theory_ clip into a mountain.

**Comment by mibby** [comment]
Is it feasible to hook into multiverse's generator if it exists to prevent the error? Or catch the verbose if it's harmless?

**Comment by Efnilite** [comment]
I don't want to depend on Multiverse, and I don't think I can catch the error since it's internal. Currently, there's also basically no alternative than using the method that creates this error (unless I try something with reflection). I don't think removing that error is very important, but I might do it eventually.

**Comment by mibby** [comment]
Sure, no problem. If it isn't an issue, I'll just ignore it. Just seems abnormal since the verbose warning seems to indicate it's improper somehow.
