### ISSUE TITLE
Possibility to edit the options GUI to remove settings?

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#16]
Is it possible to edit the options menu GUI so you can remove settings (such as gamemode) so they aren't even visible, even if players don't have permission access to it?

**Comment by Efnilite** [comment]
So you want a permission-based GUI? If they don't have the `witp.gamemode` permission, it doesn't show?

**Comment by mibby** [comment]
Rather, a GUI.yml file so you can edit the GUI items such as name, lore, icon, position, and outright remove certain functions. Just hiding the GUI item if you don't have permission would look odd since it would leave holes. I would want to reshuffle things around and remove the gamemode toggle entirely.

**Comment by Efnilite** [comment]
Currently reshuffling already happens with the top layer of items, so it shouldn't be hard to implement. Currently names and lores of all the items in the GUI can be changed in ìtems.yml`.

**Comment by Efnilite** [comment]
Added a few commits back.
