### ISSUE TITLE
Reload command is not functional in-game.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#18]
Compiled as of https://github.com/Efnilite/Walk-in-the-Park/commit/2f21af98ebc02d0df37b80ae981382070c839566

The reload command ``/witp reload`` does not seem to be functional in-game. It only seems to work from console. Nothing is outputted when using the command.

```
permissions:

    # If permissions are enabled
    enabled: true
```

I also tried giving myself a wildcard permission (``witp.*``) in case the reload permission was hidden.

**Comment by mibby** [comment]
Reloading from console also doesn't work to add new commands to the whitelist if you make config changes.

**Comment by Efnilite** [comment]
Added all config files to reload, thanks for reporting. Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/6ef383e1d30f0f42d92e92fee60d59da3a2f597f.

**Comment by mibby** [comment]
@Efnilite ``/witp reload`` still doesn't work in-game.

**Comment by Efnilite** [comment]
Are you sure you're opped? I'll add a no permission message anyway.

**Comment by mibby** [comment]
I'm not OP in the vanilla sense, but grouped Admin with all wildcard permissions (``*``). Same with ``witp.*``. I assume you don't have a permission check in place for ``witp.reload``?

**Comment by Efnilite** [comment]
I added a `witp.reload` permission, should be fine now
