### ISSUE TITLE
Save player preferences to sql database.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#22]
Would it be possible to save the player's preferences to the sql database? Currently preferences (WITP options) reset every time you rejoin the arena. A player may prefer to have their time always at a specific point, a style they always use, a certain comfort block lead, or messages they never want to see.

Having an option to choose what gets saved / used, or at least the first 3 options (style/lead/time), may be a nice quality of life change.

**Comment by Efnilite** [comment]
This feature is in development, which means I'm still testing it and I have indeed found that it doesnt work sometimes, still working on that.
