### ISSUE TITLE
High-score / leaderboard seems to not save properly & gets overwritten with a lower value when you disconnect from the server.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#24]
**Describe the bug**
The leaderboard high-score doesn't seem to save properly. If you disconnect in any fashion, your last played score is set as your current new leaderboard highscore. 

**To Reproduce**
1. Join WITP
2. Set a score of 10.
3. Quit.
4. Your highscore is 10.
5. Join WITP
6. Set a score of 1
7. Quit
8. Disconnect from server
9. Reconnect to server
10. Your leaderboard / high score is now 1.

**Edit:** Doing some more testing, it seems to set a new high score (even if it's lower than the last time you played) the first time you re-join the parkour game and get a score & fall (reset).

i.e.

Play parkour > get a score of 10 > leave parkour > rejoin parkour > get a score of 1 > goodbye highscore.

**Screenshots**
Bryn complained about their score resetting so I went in to check their total.
![link](https://i.imgur.com/z66LtCR.png)
Then they played a game and said their new score was lower.
![link2](https://i.imgur.com/fwQYTGp.png)

**Errors**
None.

**Versions**
- Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/2f21af98ebc02d0df37b80ae981382070c839566
- Paper dev 467 (Spigot 1.16.5)

**Additional context**
Using MySQL database.

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/01146d59ea97780ff41f83805aeba1988d36de16
