### ISSUE TITLE
Leftover debug verbose.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#25]
Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/01146d59ea97780ff41f83805aeba1988d36de16

https://github.com/Efnilite/Walk-in-the-Park/blob/01146d59ea97780ff41f83805aeba1988d36de16/src/main/java/dev/efnilite/witp/WITP.java#L248

https://github.com/Efnilite/Walk-in-the-Park/blob/01146d59ea97780ff41f83805aeba1988d36de16/src/main/java/dev/efnilite/witp/WITP.java#L251

https://github.com/Efnilite/Walk-in-the-Park/blob/01146d59ea97780ff41f83805aeba1988d36de16/src/main/java/dev/efnilite/witp/WITP.java#L259

Console spams  ``[22:10:43] [Server thread/INFO]: [WITP] interact call`` non-stop.

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/11789e232b529465770513c7334f085cdc87c9fd
