### ISSUE TITLE
Permission enabling does not block commands from working if you don't have permission -- only the GUI.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#26]
**Describe the bug**
```
# Options for permissions.
# These permissions are used to determine which things the player can change.
# List: https://github.com/Efnilite/Walk-in-the-Park/wiki/Permissions
permissions:

    # If permissions are enabled
    enabled: true
```

Despite permissions being enabled, players are able to use WITP commands they shouldn't have access to. A player was able to use the command ``/witp gamemode`` to enter spectate mode (and subsequently create inventory loss because of it).

**To Reproduce**
1. Enable setting.
2. Give permissions except gamemode.
3. Can't use gamemode in GUI.
4. Can use gamemode in command manually.

**Versions**
- Compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/01146d59ea97780ff41f83805aeba1988d36de16

**Additional context**

Gave only these permissions to the default group.
```
- witp.difficulty
- witp.fall
- witp.lead
- witp.leaderboard
- witp.particles
- witp.scoreboard
- witp.special
- witp.structures
- witp.style
- witp.time
```

**Comment by Efnilite** [comment]
Fixed in https://github.com/Efnilite/Walk-in-the-Park/commit/a6ac5cf068ad2f5abfd6c1eb29d194d0e6d0c63d

**Comment by mibby** [comment]
Confirmed seems fixed, thanks.
