### ISSUE TITLE
Spectator Mode Errors / Bugs

### ISSUE THREAD

**Issue by slooshied** [Efnilite/Walk-in-the-Park#3]
**Describe the bug**

When spectating another player, sometimes player cannot go back in to normal gamemode.

When going to hub and returning to world, player is teleported in normal game mode to player they were spectating's island
Player also recieves red out of bounds overlay when leaving spectator to normal island when the gui works properly

**To Reproduce**
1. Go to 'spectate'
2. Attempt to leave either by gui or command

**Screenshots**

**Errors**
Check your console for errors that might've occured. These could help greatly in finding the issue.

[Error.txt](https://github.com/Efnilite/Walk-in-the-Park/files/5790169/Error.txt)

**Versions**
- Plugin version 1.8.0
- Spigot/Paper version 1.16.4 Latest Version

**Additional context**

**Comment by Efnilite** [comment]
Fixed in latest commit, thanks for reporting.
