### ISSUE TITLE
WITP returning players to join location on quit is breaking NPC skins from loading.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#31]
**Describe the bug**
Quitting WITP and returning to the join location -- spawn hub in my case -- seems to break NPC skins from loading. I presume this is because it's returning at the same tick as NPC skins loading / being sent to the client.

**To Reproduce**
1. Join WITP
2. Quit WITP
3. NPC Skins don't load on return.

**Screenshots**
![link](https://i.imgur.com/C1gRnBf.png)

How it normally is suppose to look.
![link](https://i.imgur.com/3zcfVyF.png)

**Errors**
None.

**Versions**
- Tuinity dev 456 (Paper 1.16.5)
- WITP compiled as of commit https://github.com/Efnilite/Walk-in-the-Park/commit/f70e3186af91c878054abf888ed3e143fe44433a
- Citizens 2.0.27 dev 2268

**Additional context**
NPC skins load fine every other teleport.

Teleport to player -> go back with ``/spawn`` - fine.
Teleport to player -> go back with ``/back`` - fine.
Teleport to player -> go back with ``/home`` - fine.
Teleport to player -> go back with ``/warp`` - fine.
Use a random teleport command / function -> go back to spawn - fine.
Disconnect -> reconnect - fine.

It's only with WITP returning the player back to the spawn world / hub location does it break NPCs. I assume it would need a couple tick delay or something. Or changing the teleporting logic to match Essentials. Alternatively, using PaperLib API for async chunk loading? https://github.com/PaperMC/PaperLib

**Comment by mibby** [comment]
I might have found a temp solution by changing ``player-join-update-delay-ticks: 60`` to ``player-join-update-delay-ticks: 100`` in Citizens. Forces skins to load slower (after 5s) but seems to fix them more often than not.

**Comment by Efnilite** [comment]
Can you try with the latest commit? I added the chunk loading stuff. If it doesn't work, I'll remove it since it's a LOT of extra file size that would basically make no impact.

**Comment by mibby** [comment]
Sorry, I wasn't able to test when you added PaperLib. Testing the release build of v2.1 (without PaperLib), NPC skin loading does seem to be fixed. It breaks significantly less often with the default Citizens ``player-join-update-delay-ticks: 60``. However the teleport on return seemed a bit slower. Probably not that big of a deal if it's safer overall.

**Comment by Efnilite** [comment]
`A bit slower` probably isn't a big issue, glad it works, will be closing this.
