### ISSUE TITLE
Option to disable update checker.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#32]
Would it be possible to add an option to disable update checking? As found in many other plugins. Sometimes you intentionally stay outdated due to issues or use dev builds and have the plugin complain it is not the latest stable release. 

I'd personally prefer to disable the update checking for making connection requests to check and because I use dev builds.

**Comment by Efnilite** [comment]
Added in https://github.com/Efnilite/Walk-in-the-Park/commit/17735a59dfec3b874cb25cfb0d2cbb0587021ceb
