### ISSUE TITLE
suggestion: New sql table "game_history"

### ISSUE THREAD

**Issue by Miracusa** [Efnilite/Walk-in-the-Park#35]
It would be nice if there was an option to enable a "game-logging" option.
Enabling it could put every played game with coresponding data (uuid,blocks, time, settings) into a table.

This would make it possible to develop some kind of leaderboard for the serverwebsite or similiar. 
Settings dos sound strange at first, but would be needed for comparison (because a game played with "super easy" settings should not count the same as one played with "super hard settings")

**Comment by Efnilite** [comment]
This is a good idea, but might take a while to implement since it's quite difficult to deal with settings and how to make it easy for people to understand how difficult a run was.

**Comment by Efnilite** [comment]
Added in latest version
