### ISSUE TITLE
One-time score threshold rewards.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#38]
Would it be possible to add support for one-time score threshold rewards? For example rewarding someone for reaching a score of 1,000 but they only get that reward once (i.e. a tag or permission unlock). Currently if you use commands on score rewards, it would reward every time a person meets that threshold if they restart. 

Could flag the player if they've reached that score reward before in the database file.

**Comment by Efnilite** [comment]
I'm currently working on this feature but it might take a while to add since databases are hard ;-;

**Comment by Efnilite** [comment]
This was added in v3.1.0 -- finally lol
