### ISSUE TITLE
Error saving world?

### ISSUE THREAD

**Issue by wattywatty14** [Efnilite/Walk-in-the-Park#4]
**Describe the bug**
Console error.

**To Reproduce**
Just a console error I'm getting?

**Errors**
https://paste.ubuntu.com/p/FDqWRPw4Z3/

**Versions**
- Plugin version 1.9
- Spigot/Paper version git-Paper-400 (MC:1.16.4) 

**Additional context**
N/A

**Comment by Efnilite** [comment]
Fixed it by removing the save call (wasn't even necessary to begin with), thanks for reporting :)
