### ISSUE TITLE
Some players appears in the same island as other person

### ISSUE THREAD

**Issue by AllPlayed** [Efnilite/Walk-in-the-Park#44]
**Describe the bug**
Some players appear in the island of another player and a big error appears in the console. They can both play but the blocks just are mixed

**To Reproduce**
It is very hard to reproduce and I don't know why it happened

**Screenshots**
https://i.imgur.com/fNiDXK9.png
https://i.imgur.com/sE3VTNH.png
https://i.imgur.com/XPgHP62.png

**Errors**
`09.05 19:20:57 [Server] ERROR [WITP] Point assignment after confirmation has gone terribly wrong - regenerating..
09.05 19:20:57 [Server] ERROR [WITP] Generator of player is null while trying to unregister!
09.05 19:20:57 [Server] ERROR Could not pass event InventoryClickEvent to WITP v2.3c
09.05 19:20:57 [Server] INFO java.lang.NullPointerException: null
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.player.ParkourPlayer.updateScoreboard(ParkourPlayer.java:168) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.player.ParkourPlayer.setDefaults(ParkourPlayer.java:111) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.player.ParkourPlayer.register(ParkourPlayer.java:651) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.player.ParkourPlayer.register(ParkourPlayer.java:602) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.player.ParkourUser.unregister(ParkourUser.java:89) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.player.ParkourSpectator.<init>(ParkourSpectator.java:33) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.api.gamemode.SpectatorGamemode.lambda$handleItemClick$0(SpectatorGamemode.java:50) ~[?:?]
09.05 19:20:57 [Server] INFO at dev.efnilite.witp.util.inventory.InventoryBuilder$ClickHandler.onClick(InventoryBuilder.java:168) ~[?:?]
09.05 19:20:57 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor270.execute(Unknown Source) ~[?:?]
09.05 19:20:57 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2687) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:20:57 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-584]
09.05 19:21:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`

**Versions**
- Plugin version: 2.3c
- Spigot/Paper version: Paper-584

**Comment by Efnilite** [comment]
Thought I had fixed this, will be looking to try and fix it. Thanks for reporting.

**Comment by Efnilite** [comment]
This will be fixed in the latest release - I fixed the error part, but it still kicks players when it happens (which is rarely). I don't know how this happens, but sometimes it just does. Thanks for reporting!
