### ISSUE TITLE
Detect VoidGen plugin before warning.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#48]
https://github.com/Efnilite/Walk-in-the-Park/commit/6b8c40c5fb877b110480f229d1921928f5b4d822#diff-0717f5192199c96a9086a0990926be912ea172213d88613c6e9fa76eb7aabb8eR178-R181

I use the VoidGen plugin for creating void worlds with Multiverse. Would it be possible to not complain if this plugin is found instead of requiring WVoidGen only?

https://www.spigotmc.org/resources/voidgen.25391/

**Comment by Efnilite** [comment]
Good idea, currently I only have it so it complains (which I know is annoying) since a lot of people report the issue.

**Comment by Efnilite** [comment]
Added in a6765975e0372944c8ed63a55559d6450d65c764, thanks for suggesting!
