### ISSUE TITLE
Red corners and very limited interactions in returning world

### ISSUE THREAD

**Issue by Pette91** [Efnilite/Walk-in-the-Park#51]
**Describe the bug**
When I and my players on the server join and later leave the parkour (with all kinds of commands; parkour/witp leave, homes, back, etc.), the HUD has red corners and you can't interact with doors or even destroy any blocks. I can though mount horses. The only way to "fix" it is to re-connect to the server or switch to other worlds (like nether or the end).

**Screenshots**
<img src="https://i.ibb.co/1K8Ryxr/2021-07-30-13-55-58.png">

**Errors**
No errors in console or in-game chat.

**Versions**
- Java JDK 16.0.1
- Paper 1.16.5 (783)
- WITP 2.4e

**Additional context**
I'm using Multiverse Core and VoidGen among other plugins. The world is not named "world", I've changed to the correct one in the config file (fall-back world).

**Comment by Efnilite** [comment]
Does the red line only appear when not using `/witp leave` or does it still occur anyway?

**Comment by Pette91** [comment]
It appears anyway

**Comment by Pette91** [comment]
It seems to the red corners doesn't appear when you're running optifine, but the other described problems still occur.

**Comment by Efnilite** [comment]
I took a look and have no idea how this is happening, nobody so far has reported a similar situation, so I just decided to add a config option so you can disable the world border at the end of a player's area.

It's not likely a player will ever reach this border to begin with, so it might as well be disabled if you're having issues with it. This feature will be added in the next update, which will *probably* be in the next few days.

Thanks for reporting!
