### ISSUE TITLE
Option to disable update checker.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#52]
Simple request for improvement. 

An option to disable the update checker so WITP isn't checking for a new version every restart / OP join. Useful if you intentionally stay out of date due to an upstream bug or are testing newer commits. I always prefer to disable update checkers in plugins to reduce http calls & notification spam.

**Comment by Efnilite** [comment]
This was previously a feature, but removed it since more than half of people were using outdated versions, but I'll add it again

**Comment by Yurinann** [comment]
![image](https://user-images.githubusercontent.com/75569395/134931931-ecdf7216-74b6-4f5a-9c67-6ad0183a796e.png)
anyway maybe a wrong update-check.

**Comment by Efnilite** [comment]
> ![image](https://user-images.githubusercontent.com/75569395/134931931-ecdf7216-74b6-4f5a-9c67-6ad0183a796e.png)
> anyway maybe a wrong update-check.

what do you mean

**Comment by Yurinann** [comment]
Sorry i may not have made it clear. I checked that I am the latest version on spigotmc but there is still this prompt

**Comment by mibby** [comment]
I can confirm https://github.com/Efnilite/Walk-in-the-Park/commit/4ddbc27e398400be63e9968b64cdb8b050653085 works great, thanks! I'll leave the ticket up for you to close if the version checker is returning outdated on the latest release.

**Comment by Efnilite** [comment]
> Sorry i may not have made it clear. I checked that I am the latest version on spigotmc but there is still this prompt

I haven't updated the Spigot version yet but I've added it, so expect to see it soon :)
