### ISSUE TITLE
subCommand leaderboard input error

### ISSUE THREAD

**Issue by Yurinann** [Efnilite/Walk-in-the-Park#53]
**Describe the bug**
When inputting a non-integer parameter, an error is reported.

**To Reproduce**
1. /witp leaderboard "no int"
2. error

**Screenshots**
No.

**Errors**
https://paste.dismail.de/?0c361c35d17bead4#DM5DcMu9gNUwS2UHARhSmvh9byj1Xz3bLqy83vVqVteb

**Versions**
latest plugin version & purpur 1.16.5 latest

**Additional context**
I think it can be added here to remind of wrong parameters

**Comment by Efnilite** [comment]
Fixed in 0979d5f63992cc99d6b1cb8f3a5bccfe42778a45, thanks!
