### ISSUE TITLE
The leaderboard is not displayed

### ISSUE THREAD

**Issue by Yurinann** [Efnilite/Walk-in-the-Park#54]
**Describe the bug**
Unable to use command to get leaderboard. No error.

**To Reproduce**
1. /witp leaderboard 1
2. No display, no error 

**Screenshots**
No.

**Errors**
No.

**Versions**
- Plugin version: Latest version.
- Spigot/Paper version: purpur latest.

**Additional context**
#53 Is it because of this?

**Comment by Yurinann** [comment]
supplement: "/witp leaderboard" is normal.

**Comment by Efnilite** [comment]
Fixed in a70cee531dd928b395ae58eb8428c624aad0441d, thanks for reporting
