### ISSUE TITLE
[Suggestion] Continuous jump score increase

### ISSUE THREAD

**Issue by Yurinann** [Efnilite/Walk-in-the-Park#55]
It seems that the score is now recorded in accordance with the points that fall on the block.
I think it is possible to give more points rewards when skipping multiple squares in a row.

**Comment by Efnilite** [comment]
The point of a score is the show how many blocks the player has jumped, skipping shouldn't give any points in my opinion, because you're rewarding players for doing nothing. I'll consider adding an option where you can turn that on though.
