### ISSUE TITLE
[ERROR]: Could not load 'plugins/WITP-2.9.1.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by evo0616lution** [Efnilite/Walk-in-the-Park#69]
**Describe the bug**
Hello, I just downloaded WITP and placed it in my plugin folder. It returned this error: `[10:22:53 ERROR]: Could not load 'plugins/WITP-2.9.1.jar' in folder 'plugins'` 

I'm using Minecraft 1.17.1, Java 11 and Paper 1.17.1.

I downloaded the latest version of WITP. Please help me, thanks!

**Comment by Efnilite** [comment]
Please post the full stack trace. Right now I cant know what caused it so posting it will help a lot :)

**Comment by Efnilite** [comment]
I will add Throwable prevention to startup and shutdown nonetheless to stop the plugin from disabling on an error, but this also could be because of a very rare error, idk

**Comment by evo0616lution** [comment]
> Please post the full error and stack trace (there should be a message after that error). Right now I cant know what caused it so posting it will help a lot :)

there's no error printed afterwards D:

**Comment by Efnilite** [comment]
Uhh, is there one somewhere in the start log?

**Comment by Efnilite** [comment]
Can you try the latest build? Maybe it works now.

**Comment by evo0616lution** [comment]
> Can you try the latest build? Maybe it works now.

I have the latest build and it didn't print any errors except "Couldn't be installed" :/

**Comment by Efnilite** [comment]
Ill continue trying to find what's causing it, sorry for the inconvenience
