### ISSUE TITLE
Infinite points with one error

### ISSUE THREAD

**Issue by eloo95** [Efnilite/Walk-in-the-Park#7]
When the first block is at the island you can sneak onto the block and back to the island and you get 1 point. By repeating this process you can cheat the highscore.

**Comment by Efnilite** [comment]
I've known about this issue for a while but have struggled to find a solution. Will think about how to fix it (I already have a rough idea). Nonetheless, thanks for reporting.

**Comment by eloo95** [comment]
I have now temporarily solved it like this
saveing the last location and check if is not equal
`if(!current.getLocation().equals(hotfixLocation)) {
                                score++;
                                totalScore++;
                                hotfixLocation = current.getLocation();
                            }`

**Comment by Efnilite** [comment]
Fixed, thanks for reporting
