### ISSUE TITLE
Anyone else experiencing generation delay?

### ISSUE THREAD

**Issue by Strahilchu** [Efnilite/Walk-in-the-Park#70]
**Describe the bug**
I was hopping around and the blocks were not spawning ahead of me fast enough and I fell, looked up as I was falling and the blocks spawned.

Happens consistently, to another player as well.

Server MSPT was below zero so it couldn't be lag
ping was between 10 and 20ms so it could've have been connection

Could still be something on my end but wanted to see if anyone else has encountered something like this in latest version?

Not sure if it's even a bug yet so feel free to close this issue or if it's not the correct place to ask a question!

Thank you :)

**Comment by Efnilite** [comment]
I'm currently looking into this. I have been having the same issue. Somehow blocks get set but theyre invisible for a while. If you wanna temp fix this just set your lead to a higher number.

**Comment by Efnilite** [comment]
I have concluded it to be blocks spawning in a chunk which has never had a block set in it, however I have yet to find a fix for it. I'll keep you updated!

**Comment by Efnilite** [comment]
This has been fixed in 03a84b9205ae1722ba120fb6468c5af75bd43f2f. Thanks for reporting!
