### ISSUE TITLE
Player racing (feature suggestion)

### ISSUE THREAD

**Issue by DrakePork** [Efnilite/Walk-in-the-Park#71]
The ability for two players to race eachother to see who gets the furthest, either the first one to lets say 100 score, or the first one to fall. The players could possibly choose which type of race it would be, like if its first to fall or choose first to X score. 

The winner then either gets a price set by the server, or maybe the players can choose to bet items/money.

**Comment by Efnilite** [comment]
This exactly is already a feature in the premium addon, so unfortunately I won't be adding it to the free version, but thanks for suggesting anyway :)
