### ISSUE TITLE
WITP is keeping spawn in memory again.

### ISSUE THREAD

**Issue by mibby** [Efnilite/Walk-in-the-Park#78]
https://github.com/Efnilite/Walk-in-the-Park/blob/a72d0ebedb1fbd67d93a4ab813b8c46fd3bcf207/witp/src/main/java/dev/efnilite/witp/hook/MultiverseHook.java#L57

Was this intended to be set true? I thought it was discussed to keep false because there's no reason to keep the spawn chunks loaded when everyone's spawn island is in different locations. Unnecessary memory usage and chunk ticking.

**Comment by Efnilite** [comment]
Pretty sure this was collateral damage in trying to find a fix for the delay in the blocks appearing. Seems I forgot to change it back, but I will set it to false again next commit. Thanks for reporting.

**Comment by Efnilite** [comment]
Fixed in 093d8446909e91883305bf8bc25111bafd0d501a.
