### ISSUE TITLE
Lagging the server

### ISSUE THREAD

**Issue by irishgreencitrus** [Efnilite/Walk-in-the-Park#8]
Server is lagging much more with this plugin enabled than disabled

![image](https://user-images.githubusercontent.com/43090499/105165268-ffd84c80-5b0d-11eb-854d-569dcb36bbfa.png)

Paper stopped responding too after a player tried to join the game. Not even joining the parkour lagged the server, just joining the servers hub lagged it so much it stopped responding

- Latest Plugin
- Paper434-1.16.5

**Comment by irishgreencitrus** [comment]
Disabling Bungeecord partially helps. It allows players to at least join without a lagspike. I didnt realise it was enabled by default but when you execute a command you still get a massive lagspike followed by a either nothing happening or being kicked for 'Flying is not enabled on this server'

**Comment by Efnilite** [comment]
> 
> 
> Disabling Bungeecord partially helps. It allows players to at least join without a lagspike. I didnt realise it was enabled by default but when you execute a command you still get a massive lagspike followed by a either nothing happening or being kicked for 'Flying is not enabled on this server'

I currently have no idea on what is happening, this really shouldn't be happening. I don't know how much memory you're using, but maybe giving it more memory might help (maybe you're using something like 100 mb? I only tested with 500.)

**Comment by irishgreencitrus** [comment]
> > Disabling Bungeecord partially helps. It allows players to at least join without a lagspike. I didnt realise it was enabled by default but when you execute a command you still get a massive lagspike followed by a either nothing happening or being kicked for 'Flying is not enabled on this server'
> 
> I currently have no idea on what is happening, this really shouldn't be happening. I don't know how much memory you're using, but maybe giving it more memory might help (maybe you're using something like 100 mb? I only tested with 500.)

I'm using 6gb of ram and an update. When you execute /witp join, you join for a split second and get kicked for flying. Another thing that is high on my timings in essentials spawn, so that could possibly be messing with it

**Comment by Efnilite** [comment]
> 
> 
> > > Disabling Bungeecord partially helps. It allows players to at least join without a lagspike. I didnt realise it was enabled by default but when you execute a command you still get a massive lagspike followed by a either nothing happening or being kicked for 'Flying is not enabled on this server'
> > 
> > 
> > I currently have no idea on what is happening, this really shouldn't be happening. I don't know how much memory you're using, but maybe giving it more memory might help (maybe you're using something like 100 mb? I only tested with 500.)
> 
> I'm using 6gb of ram and an update. When you execute /witp join, you join for a split second and get kicked for flying. Another thing that is high on my timings in essentials spawn, so that could possibly be messing with it

It might be. If you could, try temporarily deleting (or moving your plugins to another folder for the time being) and only run Walk in the Park. You can use this to test if it's really down to the plugin. Even if it isn't, I'll still try to optimize joining as much as possible because I had no idea this could happen.

**Comment by irishgreencitrus** [comment]
Here's my current timings to give you an idea 
https://timings.aikar.co/?id=eb507547c1674d3dae4611eed111d257

**Comment by Efnilite** [comment]
I have absolutely now idea on how this is happening - this might take a while to fix. In the meantime, you might get away with using an older version of the plugin (like 1.9b, 1.9a or 1.8). I'll look into this ASAP.

**Comment by irishgreencitrus** [comment]
I'll try it without Essentials spawn, but the other thing I have is multiverse, which also changes spawning. EssentialsX Spawn is optional and i don't really need it anymore, but I cannot delete multiverse as i need it for everything else on my server

**Comment by irishgreencitrus** [comment]
Hmm. I've disabled EssentialsX Spawn and i no longer get kicked for flying, but the server still doesn't respond long enough to get the  `DO NOT REPORT THIS TO PAPER THE SERVER HAS NOT RESPONDED FOR x SECONDS` thread dump.

**Comment by Efnilite** [comment]
This could be possibly fixed (???) in the upcoming release. So far I haven't heard of anyone else who has this problem, so it might be a one-off thing and I really can't think of why this is happening.
