### ISSUE TITLE
Leaderboard Display Issue

### ISSUE THREAD

**Issue by Kekedekes** [Efnilite/Walk-in-the-Park#80]
![image](https://user-images.githubusercontent.com/106196643/170850560-8ae49e3f-53b5-4a94-87b5-5909ae2e11c7.png)

Leaderboard is not working currently. Using latest version of plugin and DecentHolograms. 

When I join a WITP session and then leave, it properly updates the leaderboard on the hologram. But when I logout of the game, it shows what appears on the attached image.

**Comment by Efnilite** [comment]
Is this still an issue or did you close it intentionally? Just making sure :>
