### ISSUE TITLE
Feature Request: Same World

### ISSUE THREAD

**Issue by strich3** [Efnilite/Walk-in-the-Park#84]
What this feature should do:

If you jump to a certain location the Blocks should pop up before you so anyone can jump the same parkour (Like in a Lobby it would be very usefull), would be something like that possible?

**Comment by Efnilite** [comment]
This is already a feature being worked on for the premium expansion: Infinite Parkour+. You can view all planned features in the screenshots below and in the #ipplus channel in Discord. 

![image](https://user-images.githubusercontent.com/35348263/178559027-1336fe42-ae56-42ef-9c45-a8842112d8ad.png)
![image](https://user-images.githubusercontent.com/35348263/178559037-08064f55-6261-485d-89fe-06636786929b.png)
