### ISSUE TITLE
[3.5.3] Task generated an exception

### ISSUE THREAD

**Issue by noiverre** [Efnilite/Walk-in-the-Park#86]
**Describe the bug**
Only happened in console, I don't really know what happened in game

**To Reproduce**
1. Install IP
2. Install Spark for bukkit
3. Run /spark heapsummary to force do gc
4. Sometimes, an exception thrown

**Screenshots**
-

**Errors**
[Here](https://paste.gg/p/anonymous/2adb442c801c4141b58f39a2e9b44623)

**Versions**
- IP 3.5.3
- [⚡] spark v1.9.20
- This server is running Paper version git-Paper-61 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)

**Additional context**
I don't use any world managers

**Comment by Efnilite** [comment]
Fixed in 9f2f5d4fac1e2be0ba139d87068362eb1e4b3e70, thanks for notifying me :) 
Official release with this fix should arrive in a few days.
