### ISSUE TITLE
Plugin still called WITP in /plugins

### ISSUE THREAD

**Issue by Folas1337** [Efnilite/Walk-in-the-Park#89]
**Describe the bug**
When using /pl or /ver the plugin is still called WITP instead of IP or InfiniteParkour which is a little inconsistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/39222968/185788207-c8019bdb-5b7b-4376-a9fa-c276c85942ee.png)

**Versions**
- Plugin version 3.8.0
- Paper version 1.19.2 build 130

**Comment by Efnilite** [comment]
This is done to keep the folder name the same. Currently, every server has their data in plugins/WITP, but if the name were to change to IP, it would mean the new folder that would be checked would be plugins/IP. If this doesn't exist, the plugin will assume it's a new installation, even though it isn't. I might fix this later by moving all the files to the plugins/IP folder :)

**Comment by Efnilite** [comment]
Fixed in v4.0.0.
