### ISSUE TITLE
Suggestion: Adding config option to change number of blocks generated in front of player.

### ISSUE THREAD

**Issue by McFinnious** [Efnilite/Walk-in-the-Park#9]
I'm looking for a faster, more challenging setup of your plugin. Having the option to put more blocks in front of the player would be awesome!

**Comment by Efnilite** [comment]
You got it.

**Comment by Efnilite** [comment]
Added in https://github.com/Efnilite/Walk-in-the-Park/commit/edaf31756fd53bc39e762dceb42889fcc8aa1fa9, thanks for commenting!
