### ISSUE TITLE
Change **delete-on-reload**

### ISSUE THREAD

**Issue by moderator10000078** [Efnilite/Walk-in-the-Park#91]
**Describe the bug**
This option works only if the command, stop, restart, or reload was written, but the servers can be turned off without these commands, for example, if it was crashed by a strong lag machine, and then this function will not work

**Versions**
- IP-4.0.0

**Solving the problem**
I think the most obvious thing is to also reinstall the world during server startup

**Comment by Efnilite** [comment]
Do you have delete-on-reload set to true or false?

**Comment by Efnilite** [comment]
Fixed in 9a4b93a9c2dbc325279900440c4463e6c367555b, thanks for telling me :)
