### ISSUE TITLE
Turning off chat does nothing

### ISSUE THREAD

**Issue by Folas1337** [Efnilite/Walk-in-the-Park#92]
**Describe the bug**
Turning off the chat functionality does not seem to have any effect, neither negating the permission ip.settings.chat nor setting the node default-values.settings.chat to false in the config.yml

**Versions**
- Plugin version: 4.0.0
- Paper version 1.19.2 build 136

**Comment by Folas1337** [comment]
Also using vilib 1.1.0

**Comment by Efnilite** [comment]
Fixed in 58d645fdfef43c3cbb3443802c5b444d21185ddc, thanks for reporting.
