### ISSUE TITLE
Parkour settings not working in ingame mode

### ISSUE THREAD

**Issue by EneRGO22** [Efnilite/Walk-in-the-Park#94]
**Describe the bug**
Parkour settings not working in ingame mode

https://user-images.githubusercontent.com/68811273/190084846-1df9b610-fc2e-4821-82ac-d445a951a1b0.mp4

**Versions**
- 4.0.1
- ![image](https://user-images.githubusercontent.com/68811273/190084406-dae8e214-dd00-40b4-9a6a-8357e62b71b7.png)

**Comment by Efnilite** [comment]
Empty menus will be removed in the next update :)

**Comment by Efnilite** [comment]
Fixed in 40fdd5a10ae0e4dffb3d990b920ab0a305085738, you should see it in the next update
