### ISSUE TITLE
Miss locales key

### ISSUE THREAD

**Issue by YKDZ** [Efnilite/Walk-in-the-Park#95]
**Describe the bug**
There seems a missed locales key in the locales yml.
![Snipaste_2022-10-01_12-54-05](https://user-images.githubusercontent.com/69898831/193393246-6007197b-b833-4d45-ab94-f855a4afda47.png)
This "Default" in the style gui can not be translated

**Versions**
- IP-4.0.3
- IPPlus-1.0.2
- Purpur 1.19.2

**Comment by Efnilite** [comment]
Fixed in c89f6558c088ef4280f5e8a4430e981fd58dfb9e, you'll see this change in the next update :) thanks for reporting!
