### ISSUE TITLE
Fence block that can't be jumped on 

### ISSUE THREAD

**Issue by Folas1337** [Efnilite/Walk-in-the-Park#96]
**Describe the bug**
A fence allegedly spawned on a user that couldn't be jumped on, looking like what I've provided in the screenshot. 

**To Reproduce**
Hard to reproduce something in a parkour that generates at random I think

**Screenshots**
![2022-10-07_10.54.57.png](https://user-images.githubusercontent.com/39222968/194516907-44821e69-2a05-4796-ab71-2c34caaae68f.png)

**Errors**
No errors in the console during the time it happened

**Versions**
- Plugin version: 4.0.3
- Spigot/Paper version: 1.19.2 build 194

**Comment by Folas1337** [comment]
And apparently another impossible one:
![2022-10-07_11.11.38.png](https://user-images.githubusercontent.com/39222968/194518619-44b7fa8a-047a-4704-87fc-aa3358e5dda1.png)

Oak log is too far to jump on and if you jump onto the slab, you're stuck in basically the same situation as with the fence posted before.

**Comment by Efnilite** [comment]
Fixed in 6016848b1568c9c9029e0e8bc4138941b8b12ca6, thanks for reporting :)
